apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: phpmyadmin
  ports:
  - name: https
    protocol: TCP
    port: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        imagePullPolicy: Never
        image: phpmyadmin_image
        ports:
        - containerPort: 5000